### PR TITLE
Fix catkin files

### PR DESCRIPTION
**Pull request by mintar**
This patch fixes several errors reported by catkin_lint. This also
solves compilation problems when rosjava is installed.

### CODE REVIEW

**Comment by mintar** [comment]
Ping

**Comment by v-lopez** [comment]
Thanks for the patch! My apologies for the delay accepting it.

**Comment by mintar** [comment]
No problem! :)

**Comment by mintar** [comment]
Did you forget to click "merge"? :)

**Comment by v-lopez** [comment]
Haha yeah sorry, I'm used to accepting them on gitlab which is click and forget. Here I had the chance of changing the commit message.

**Pull request merged**
